/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package patientmanagementsystem;
import java.util.*;
import java.lang.*;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import  net.proteanit.sql.DbUtils;
import javax.swing.table.*;
//import javax.naming.spi.DirStateFactory.Result;
import javax.swing.table.*;
import javax.swing.JOptionPane;
import java.sql.*;

import javax.swing.JOptionPane;
/**
 *
 * @author Raveendran
 */
public class Patients extends javax.swing.JFrame {

    /**
     * Creates new form Patients
     */
    public Patients() {
        initComponents();
        DisplayPatients();
        PatCount();
    }
Connection Con = null;
Statement St = null,St1=null;
ResultSet Rs = null,Rs1=null;
PreparedStatement add;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        appointmentsText = new javax.swing.JLabel();
        treatmentText = new javax.swing.JLabel();
        prescriptionText = new javax.swing.JLabel();
        dashboardText = new javax.swing.JLabel();
        logout1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        PhoneTb = new javax.swing.JTextField();
        DOB = new javax.swing.JTextField();
        PatGen = new javax.swing.JComboBox<>();
        AddressTb = new javax.swing.JTextField();
        AllergieTb = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        PatTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        PatNameTb = new javax.swing.JTextField();
        dateText = new javax.swing.JLabel();
        dateText1 = new javax.swing.JLabel();
        dateText2 = new javax.swing.JLabel();
        dateText3 = new javax.swing.JLabel();
        dateText4 = new javax.swing.JLabel();
        dateText5 = new javax.swing.JLabel();
        dateText6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        closeLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1265, 746));

        jPanel1.setBackground(new java.awt.Color(254, 131, 198));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 3, true));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(32, 32, 32));
        jLabel19.setText("Patients Section");

        jLabel3.setFont(new java.awt.Font("PT Sans", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(32, 32, 32));
        jLabel3.setText(" Medinova Hospital");

        appointmentsText.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        appointmentsText.setForeground(new java.awt.Color(255, 242, 249));
        appointmentsText.setText("Appointments");
        appointmentsText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appointmentsTextMouseClicked(evt);
            }
        });

        treatmentText.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        treatmentText.setForeground(new java.awt.Color(255, 242, 249));
        treatmentText.setText("Treatment");
        treatmentText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treatmentTextMouseClicked(evt);
            }
        });

        prescriptionText.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        prescriptionText.setForeground(new java.awt.Color(255, 242, 249));
        prescriptionText.setText("Prescription");
        prescriptionText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prescriptionTextMouseClicked(evt);
            }
        });

        dashboardText.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        dashboardText.setForeground(new java.awt.Color(255, 242, 249));
        dashboardText.setText("Dashboard");
        dashboardText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardTextMouseClicked(evt);
            }
        });

        logout1.setFont(new java.awt.Font("PT Sans", 1, 24)); // NOI18N
        logout1.setForeground(new java.awt.Color(255, 242, 249));
        logout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout_smol.png"))); // NOI18N
        logout1.setText("Logout");
        logout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(145, 145, 145))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel3)
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logout1)
                    .addComponent(dashboardText)
                    .addComponent(prescriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(treatmentText, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appointmentsText, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addComponent(jLabel19)
                .addGap(53, 53, 53)
                .addComponent(appointmentsText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(treatmentText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(prescriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(dashboardText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel10)
                .addGap(88, 88, 88)
                .addComponent(logout1)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(32, 32, 32));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 3, true));

        PhoneTb.setFont(new java.awt.Font("PT Sans", 0, 11)); // NOI18N
        PhoneTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneTbActionPerformed(evt);
            }
        });

        DOB.setFont(new java.awt.Font("PT Sans", 0, 11)); // NOI18N
        DOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOBActionPerformed(evt);
            }
        });

        PatGen.setFont(new java.awt.Font("PT Sans", 0, 11)); // NOI18N
        PatGen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        AddressTb.setFont(new java.awt.Font("PT Sans", 0, 11)); // NOI18N
        AddressTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressTbActionPerformed(evt);
            }
        });

        AllergieTb.setFont(new java.awt.Font("PT Sans", 0, 11)); // NOI18N
        AllergieTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllergieTbActionPerformed(evt);
            }
        });

        PatTable.setFont(new java.awt.Font("PT Sans", 0, 12)); // NOI18N
        PatTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Phone", "Address", "DOB", "Gender", "Allergies"
            }
        ));
        PatTable.setRowHeight(24);
        PatTable.setSelectionBackground(new java.awt.Color(254, 131, 198));
        PatTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PatTable);

        jButton1.setFont(new java.awt.Font("PT Sans", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 51));
        jButton1.setText("Save");
        jButton1.setBorderPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("PT Sans", 1, 16)); // NOI18N
        jButton2.setText("Edit");
        jButton2.setBorderPainted(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("PT Sans", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 51, 51));
        jButton3.setText("Delete");
        jButton3.setBorderPainted(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("PT Sans", 1, 16)); // NOI18N
        jButton4.setText("Clear");
        jButton4.setBorderPainted(false);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        PatNameTb.setFont(new java.awt.Font("PT Sans", 0, 11)); // NOI18N
        PatNameTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatNameTbActionPerformed(evt);
            }
        });

        dateText.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        dateText.setForeground(new java.awt.Color(255, 242, 249));
        dateText.setText("Address");

        dateText1.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        dateText1.setForeground(new java.awt.Color(255, 242, 249));
        dateText1.setText("Name");

        dateText2.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        dateText2.setForeground(new java.awt.Color(255, 242, 249));
        dateText2.setText("DOB");

        dateText3.setFont(new java.awt.Font("PT Sans", 0, 24)); // NOI18N
        dateText3.setForeground(new java.awt.Color(255, 242, 249));
        dateText3.setText("Patients List");

        dateText4.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        dateText4.setForeground(new java.awt.Color(255, 242, 249));
        dateText4.setText("Allergies");

        dateText5.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        dateText5.setForeground(new java.awt.Color(255, 242, 249));
        dateText5.setText("Gender");

        dateText6.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        dateText6.setForeground(new java.awt.Color(255, 242, 249));
        dateText6.setText("Phone");

        jLabel2.setFont(new java.awt.Font("PT Sans", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 131, 198));
        jLabel2.setText("Patients");

        jLabel4.setFont(new java.awt.Font("PT Sans", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Project by Mihir Panchal and Pooja Nambiar ");

        closeLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close_icon_small_forloginpage.png"))); // NOI18N
        closeLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addComponent(dateText3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jButton1)
                        .addGap(78, 78, 78)
                        .addComponent(jButton2)
                        .addGap(85, 85, 85)
                        .addComponent(jButton3)
                        .addGap(71, 71, 71)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AllergieTb, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4)
                            .addComponent(dateText4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(294, 294, 294))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeLogin))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateText6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateText1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PatNameTb, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PhoneTb, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(AddressTb, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateText2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PatGen, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateText5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(closeLogin))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateText2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateText4)
                    .addComponent(dateText1))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(PatNameTb, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateText6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PhoneTb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(DOB)
                        .addGap(18, 18, 18)
                        .addComponent(dateText5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PatGen, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AddressTb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AllergieTb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateText3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AllergieTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllergieTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AllergieTbActionPerformed

    private void DOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBActionPerformed

    private void PhoneTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneTbActionPerformed

    private void AddressTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressTbActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       if(PatNameTb.getText().isEmpty() || AllergieTb.getText().isEmpty() || AddressTb.getText().isEmpty() || PhoneTb.getText().isEmpty())
       {
           JOptionPane.showMessageDialog(this,"Missing Information");
       }else
       {
           try{
               PatCount();
               Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/patientmanagementsystem?user=root&password=MANGOstick123@");
               add =Con.prepareStatement("insert into patienttbl(patid,patname,phone,pataddress,dob,patgen,patallergies ) values(?,?,?,?,?,?,?);");
               add.setInt(1, PatId);
               add.setString(2, PatNameTb.getText());
               add.setString(3, PhoneTb.getText());
               add.setString(4, AddressTb.getText());
               add.setString(5, DOB.getText());
               add.setString(6, PatGen.getSelectedItem().toString());
               add.setString(7, AllergieTb.getText());
               int row = add.executeUpdate();
               JOptionPane.showMessageDialog(this, "Patient Added Successfully");
               Con.close();
               DisplayPatients();
               Clear();
           }catch(Exception e){
               Logger.getLogger(Patients.class.getName()).log(Level.SEVERE,null,e);
               e.printStackTrace();
           }
       }
    }//GEN-LAST:event_jButton1MouseClicked

    int Key = -1;
    private void PatTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatTableMouseClicked

        DefaultTableModel model = (DefaultTableModel)PatTable.getModel();
        int MyIndex = PatTable.getSelectedRow();
        Key = Integer.parseInt(model.getValueAt(MyIndex, 1).toString());
        PatNameTb.setText(model.getValueAt(MyIndex, 0).toString());
        PhoneTb.setText(model.getValueAt(MyIndex, 2).toString());
        AddressTb.setText(model.getValueAt(MyIndex, 3).toString());
        DOB.setText(model.getValueAt(MyIndex, 4).toString());
        PatGen.setSelectedItem(model.getValueAt(MyIndex, 5).toString());
        AllergieTb.setText(model.getValueAt(MyIndex, 6).toString());
    }//GEN-LAST:event_PatTableMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
       if(Key == -1)
       {
           JOptionPane.showMessageDialog(this,"Select The Patient");
       }
       else
       {
           try{
               
               Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/patientmanagementsystem?user=root&password=MANGOstick123@");
               add = Con.prepareStatement("update patientmanagementsystem.patienttbl set PatName='"+PatNameTb.getText()+"'"+",Phone='"+PhoneTb.getText()+"'"+",PatAddress='"+AddressTb.getText()+"'"+",DOB='"+DOB.getText()+"'"+",PatGen='"+PatGen.getSelectedItem().toString()+"'"+",PatAllergies='"+AllergieTb.getText()+"'"+" where Patid="+Key);
               add.executeUpdate();
               JOptionPane.showMessageDialog(this, "Patient Updated Successfully");
               DisplayPatients();
               Clear();
           }catch(Exception e){
               Logger.getLogger(Patients.class.getName()).log(Level.SEVERE,null,e);
               e.printStackTrace();
           }
       } 
    }//GEN-LAST:event_jButton2MouseClicked

    int PatId=0;
    private void PatCount(){
    
        try{
        St1 = Con.createStatement();
        Rs1 = St1.executeQuery("Select Max(Patid) from patientmanagementsystem.patienttbl");
        Rs1.next();
        PatId = Rs1.getInt(1)+1;
        }
        catch(Exception e)
        {}
    }
    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
       if(Key == -1)
       {
           JOptionPane.showMessageDialog(this,"Select The Patient");
       }
       else
       {
           try{
               Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/patientmanagementsystem?user=root&password=MANGOstick123@");
               add = Con.prepareStatement("Delete from patientmanagementsystem.patienttbl where Patid="+Key);
               add.executeUpdate();
               JOptionPane.showMessageDialog(this, "Patient Deleted Successfully");
               DisplayPatients();
               Clear();
               
           }catch(Exception e){
               Logger.getLogger(Patients.class.getName()).log(Level.SEVERE,null,e);
               e.printStackTrace();
           }
       } 
    }//GEN-LAST:event_jButton3MouseClicked
private void Clear()
{
    PatNameTb.setText("");
    PhoneTb.setText("");
    AllergieTb.setText("");
    AddressTb.setText(""); 
    PatGen.setSelectedIndex(-1);
    DOB.setText("");
}
    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked

        Clear();
    }//GEN-LAST:event_jButton4MouseClicked

    private void PatNameTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatNameTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatNameTbActionPerformed

    private void appointmentsTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointmentsTextMouseClicked
        new appointments().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_appointmentsTextMouseClicked

    private void treatmentTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treatmentTextMouseClicked
        new Treatments().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_treatmentTextMouseClicked

    private void prescriptionTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prescriptionTextMouseClicked
        new Prescription().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_prescriptionTextMouseClicked

    private void dashboardTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardTextMouseClicked
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardTextMouseClicked

    private void logout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout1MouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logout1MouseClicked

    private void closeLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLoginMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeLoginMouseClicked
private void DisplayPatients()
{
    
    try{
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/patientmanagementsystem?user=root&password=MANGOstick123@");
        St = Con.createStatement();
        Rs = St.executeQuery("Select* from patientmanagementsystem.patienttbl");
        PatTable.setModel(DbUtils.resultSetToTableModel(Rs));
    }catch(Exception e){
        
    }


}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patients().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTb;
    private javax.swing.JTextField AllergieTb;
    private javax.swing.JTextField DOB;
    private javax.swing.JComboBox<String> PatGen;
    private javax.swing.JTextField PatNameTb;
    private javax.swing.JTable PatTable;
    private javax.swing.JTextField PhoneTb;
    private javax.swing.JLabel appointmentsText;
    private javax.swing.JLabel closeLogin;
    private javax.swing.JLabel dashboardText;
    private javax.swing.JLabel dateText;
    private javax.swing.JLabel dateText1;
    private javax.swing.JLabel dateText2;
    private javax.swing.JLabel dateText3;
    private javax.swing.JLabel dateText4;
    private javax.swing.JLabel dateText5;
    private javax.swing.JLabel dateText6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logout1;
    private javax.swing.JLabel prescriptionText;
    private javax.swing.JLabel treatmentText;
    // End of variables declaration//GEN-END:variables
}
