
import java.util.*;
import java.lang.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
import  net.proteanit.sql.DbUtils;
import javax.swing.table.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rocker
 */
public class Prescription extends javax.swing.JFrame {

    /**
     * Creates new form Prescription
     */
    public Prescription() {
        initComponents();
        getPatient();
        getTreatment();
        displayPrescription();
        clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        appointmentsText = new javax.swing.JLabel();
        prescSectionLabel = new javax.swing.JLabel();
        treatmentText = new javax.swing.JLabel();
        dashboardText = new javax.swing.JLabel();
        patientText = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logout1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        costText = new javax.swing.JLabel();
        patientlabel = new javax.swing.JLabel();
        pName = new javax.swing.JComboBox<>();
        treatmentListText = new javax.swing.JLabel();
        mdeicineslabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PrescriptionTable = new javax.swing.JTable();
        editButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        costField = new javax.swing.JTextField();
        treatmentText2 = new javax.swing.JLabel();
        costText1 = new javax.swing.JLabel();
        medicine = new javax.swing.JTextField();
        quantityField = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        treatName = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        closeLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(254, 131, 198));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 3, true));

        appointmentsText.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        appointmentsText.setForeground(new java.awt.Color(255, 242, 249));
        appointmentsText.setText("Appointments");
        appointmentsText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appointmentsTextMouseClicked(evt);
            }
        });

        prescSectionLabel.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        prescSectionLabel.setForeground(new java.awt.Color(32, 32, 32));
        prescSectionLabel.setText("Prescriptions Section");

        treatmentText.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        treatmentText.setForeground(new java.awt.Color(255, 242, 249));
        treatmentText.setText("Treatment");
        treatmentText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treatmentTextMouseClicked(evt);
            }
        });

        dashboardText.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        dashboardText.setForeground(new java.awt.Color(255, 242, 249));
        dashboardText.setText("Dashboard");
        dashboardText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardTextMouseClicked(evt);
            }
        });

        patientText.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        patientText.setForeground(new java.awt.Color(255, 242, 249));
        patientText.setText("Patients");
        patientText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientTextMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("PT Sans", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(32, 32, 32));
        jLabel3.setText(" Medinova Hospital");

        logout1.setFont(new java.awt.Font("PT Sans", 1, 24)); // NOI18N
        logout1.setForeground(new java.awt.Color(255, 242, 249));
        logout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout_smol.png"))); // NOI18N
        logout1.setText("Logout");
        logout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(prescSectionLabel)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(treatmentText, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientText)
                            .addComponent(appointmentsText, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dashboardText)
                            .addComponent(logout1))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addComponent(prescSectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(patientText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(treatmentText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(appointmentsText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(dashboardText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(logout1)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(32, 32, 32));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 3, true));

        costText.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        costText.setForeground(new java.awt.Color(255, 242, 249));
        costText.setText("Cost");

        patientlabel.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        patientlabel.setForeground(new java.awt.Color(255, 242, 249));
        patientlabel.setText("Patient");

        pName.setBackground(new java.awt.Color(248, 237, 237));
        pName.setFont(new java.awt.Font("PT Sans", 0, 11)); // NOI18N

        treatmentListText.setFont(new java.awt.Font("PT Sans", 0, 24)); // NOI18N
        treatmentListText.setForeground(new java.awt.Color(255, 242, 249));
        treatmentListText.setText("Prescription List");

        mdeicineslabel.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        mdeicineslabel.setForeground(new java.awt.Color(255, 242, 249));
        mdeicineslabel.setText("Medicines");

        PrescriptionTable.setFont(new java.awt.Font("PT Sans", 0, 11)); // NOI18N
        PrescriptionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Patient Name", "Treatments", "Cost", "Medicines", "Quantity"
            }
        ));
        PrescriptionTable.setRowHeight(24);
        PrescriptionTable.setSelectionBackground(new java.awt.Color(254, 131, 198));
        PrescriptionTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        PrescriptionTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrescriptionTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PrescriptionTable);

        editButton.setBackground(new java.awt.Color(255, 255, 255));
        editButton.setFont(new java.awt.Font("PT Sans", 1, 14)); // NOI18N
        editButton.setText("Edit");
        editButton.setBorderPainted(false);
        editButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editButtonMouseClicked(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(255, 255, 255));
        saveButton.setFont(new java.awt.Font("PT Sans", 1, 14)); // NOI18N
        saveButton.setForeground(new java.awt.Color(0, 153, 51));
        saveButton.setText("Save");
        saveButton.setBorderPainted(false);
        saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveButtonMouseClicked(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(255, 255, 255));
        deleteButton.setFont(new java.awt.Font("PT Sans", 1, 14)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 51, 51));
        deleteButton.setText("Delete");
        deleteButton.setBorderPainted(false);
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });

        costField.setFont(new java.awt.Font("PT Sans", 0, 11)); // NOI18N

        treatmentText2.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        treatmentText2.setForeground(new java.awt.Color(255, 242, 249));
        treatmentText2.setText("Treatment");

        costText1.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        costText1.setForeground(new java.awt.Color(255, 242, 249));
        costText1.setText("Quantity");

        medicine.setFont(new java.awt.Font("PT Sans", 0, 11)); // NOI18N
        medicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineActionPerformed(evt);
            }
        });

        quantityField.setFont(new java.awt.Font("PT Sans", 0, 11)); // NOI18N

        clearButton.setBackground(new java.awt.Color(255, 255, 255));
        clearButton.setFont(new java.awt.Font("PT Sans", 1, 14)); // NOI18N
        clearButton.setForeground(new java.awt.Color(0, 51, 51));
        clearButton.setText("Clear");
        clearButton.setBorderPainted(false);
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButtonMouseClicked(evt);
            }
        });

        treatName.setBackground(new java.awt.Color(248, 237, 237));
        treatName.setFont(new java.awt.Font("PT Sans", 0, 11)); // NOI18N

        jLabel2.setFont(new java.awt.Font("PT Sans", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 131, 198));
        jLabel2.setText("Prescriptions");

        jLabel4.setFont(new java.awt.Font("PT Sans", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Project by Mihir Panchal and Pooja Nambiar ");

        closeLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close_icon_small_forloginpage.png"))); // NOI18N
        closeLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeLogin)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addComponent(saveButton)
                                .addGap(70, 70, 70)
                                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(treatmentText2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(234, 234, 234)
                                .addComponent(patientlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(treatName, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(174, 174, 174)
                                .addComponent(pName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(costField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(costText, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(106, 106, 106)
                                        .addComponent(jLabel1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(189, 189, 189)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(costText1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mdeicineslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(medicine, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(110, 110, 110))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(205, 205, 205))))))
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(treatmentListText, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(closeLogin))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(patientlabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mdeicineslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(treatmentText2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(treatName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(costText)
                            .addComponent(costText1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(costField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(medicine, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveButton)
                            .addComponent(editButton)
                            .addComponent(deleteButton)
                            .addComponent(clearButton))))
                .addGap(18, 18, 18)
                .addComponent(treatmentListText, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void medicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicineActionPerformed

    Connection con;
    PreparedStatement ps;
    ResultSet rs,rs1=null;
    Statement st,st1=null;
    private void getPatient(){
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/patientmanagementsystem?user=root&password=MANGOstick123@");
            st = con.createStatement();
            rs = st.executeQuery("select PatName from patienttbl");
            while(rs.next())
            {
                String pname = rs.getString("PatName");
                pName.addItem(pname);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Treatments.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void getTreatment(){
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/patientmanagementsystem?user=root&password=MANGOstick123@");
            st = con.createStatement();
            rs = st.executeQuery("select t_name from treatment");
            while(rs.next())
            {
                String tname = rs.getString("t_name");
                treatName.addItem(tname);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Treatments.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void displayPrescription(){
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/patientmanagementsystem?user=root&password=MANGOstick123@");
            st = con.createStatement();
            rs = st.executeQuery("select * from prescription");
            PrescriptionTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(Treatments.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    int prescription_id=0;
    private void prescCount()
    {
        try{
            st1=con.createStatement();
            rs1 = st1.executeQuery("select max(presc_id) from prescription;");
            rs1.next();
            prescription_id = rs1.getInt(1)+1;
        }catch(Exception ex){ex.printStackTrace();}
    }
    private void saveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseClicked
        if(treatName.getSelectedIndex()==-1||pName.getSelectedIndex()==-1||medicine.getText().isEmpty()||costField.getText().isEmpty()||quantityField.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Information is Missing.");
        }
        else
        {
            try
            {
                prescCount();
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/patientmanagementsystem?user=root&password=MANGOstick123@");
                ps = con.prepareStatement("insert into prescription(presc_id,presc_cost,pr_Treat,quantity,medicines,pr_name) values(?,?,?,?,?,?)" ); //add pr_name later
                ps.setInt(1,prescription_id);
                ps.setString(6, pName.getSelectedItem().toString());
                ps.setInt(2, Integer.parseInt(costField.getText()));
                ps.setString(3, treatName.getSelectedItem().toString());
                ps.setInt(4, Integer.parseInt(quantityField.getText()));
                ps.setString(5, medicine.getText());
                int row = ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Prescription inserted.");
                con.close();
                displayPrescription();
                clear();
            }catch(Exception e)
            {
                Logger.getLogger(Treatments.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }//GEN-LAST:event_saveButtonMouseClicked

    
    private void clear()
    {
        treatName.setSelectedIndex(-1);
        pName.setSelectedIndex(-1);
        medicine.setText("");
        costField.setText("");
        quantityField.setText("");
        key = -1;
        
    }
    private void clearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseClicked
        clear();
        //JOptionPane.showMessageDialog(this, "Cleared");
    }//GEN-LAST:event_clearButtonMouseClicked

    int key=-1;
    private void PrescriptionTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrescriptionTableMouseClicked

        DefaultTableModel model = (DefaultTableModel)PrescriptionTable.getModel();
        int index= PrescriptionTable.getSelectedRow();
        key = Integer.parseInt(model.getValueAt(index, 0).toString());
        treatName.setSelectedItem(model.getValueAt(index,3).toString());
        pName.setSelectedItem(model.getValueAt(index,1).toString());
        costField.setText(model.getValueAt(index,2).toString());
        quantityField.setText(model.getValueAt(index,4).toString());
        medicine.setText(model.getValueAt(index,5).toString());
        
    }//GEN-LAST:event_PrescriptionTableMouseClicked

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
         if(key==-1)
        {
            JOptionPane.showMessageDialog(this, "Select prescription.");
        }
        else
        {
            try{
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/patientmanagementsystem?user=root&password=MANGOstick123@");
                ps = con.prepareStatement("delete from prescription where presc_id="+key);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Prescription Deleted.");
                displayPrescription();
                clear();
            }catch(Exception e){
                Logger.getLogger(Treatments.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }//GEN-LAST:event_deleteButtonMouseClicked

    private void editButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseClicked
        try{
            if(key==-1)
        {
            JOptionPane.showMessageDialog(this, "Select prescription to edit.");
        }
        else
        {
            try{
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/patientmanagementsystem?user=root&password=MANGOstick123@");
                ps = con.prepareStatement("update prescription set presc_cost='"+Integer.parseInt(costField.getText())+"'"+",pr_name='"+pName.getSelectedItem().toString()+"'"+",pr_Treat='"+treatName.getSelectedItem().toString()+"'"+",quantity='"+Integer.parseInt(quantityField.getText())+"'"+",medicines='"+medicine.getText()+"'"+" where presc_id="+key);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Prescription updated successfully.");
                displayPrescription();
                clear();
            }catch(Exception e){
                Logger.getLogger(Treatments.class.getName()).log(Level.SEVERE, null, e);
            }
        }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_editButtonMouseClicked

    private void patientTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientTextMouseClicked
        new Patients().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_patientTextMouseClicked

    private void appointmentsTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointmentsTextMouseClicked
        new appointments().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_appointmentsTextMouseClicked

    private void dashboardTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardTextMouseClicked
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardTextMouseClicked

    private void treatmentTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treatmentTextMouseClicked
        new Treatments().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_treatmentTextMouseClicked

    private void logout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout1MouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logout1MouseClicked

    private void closeLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLoginMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prescription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PrescriptionTable;
    private javax.swing.JLabel appointmentsText;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel closeLogin;
    private javax.swing.JTextField costField;
    private javax.swing.JLabel costText;
    private javax.swing.JLabel costText1;
    private javax.swing.JLabel dashboardText;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logout1;
    private javax.swing.JLabel mdeicineslabel;
    private javax.swing.JTextField medicine;
    private javax.swing.JComboBox<String> pName;
    private javax.swing.JLabel patientText;
    private javax.swing.JLabel patientlabel;
    private javax.swing.JLabel prescSectionLabel;
    private javax.swing.JTextField quantityField;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> treatName;
    private javax.swing.JLabel treatmentListText;
    private javax.swing.JLabel treatmentText;
    private javax.swing.JLabel treatmentText2;
    // End of variables declaration//GEN-END:variables
}
